spring:
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
        pathmatch:
            matching-strategy: ant_path_matcher
    jpa:
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    lob.non_contextual_creation : true
    h2:
        console:
            enabled: true
    datasource:
        #url: jdbc:h2:file:./spring-blog
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://132.226.20.56:5432/springblog
        #platform: postgres
        username: postgres
        password: beintech1234
    jackson:
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
        time-zone : Asia/Seoul
#        deserialization:
#            unwrap-root-value: true
#        serialization:
#            wrap-root-value: true

# https://developers.facebook.com/apps -> 새 앱 추가 -> Facebook 로그인
spring.security.oauth2.client.registration.facebook.client-id: 487654301400466
spring.security.oauth2.client.registration.facebook.client-secret: 3ec76bf19fbfeaf187a6673d1cf16411

# https://console.developers.google.com/ -> 사용자 인증 정보 -> 사용자 인증 정보 만들기 -> OAuth 클라이언트 ID
#spring.security.oauth2.client.registration.google.client-id: 564319405493-ldgbknrojsjh4m3lm187df00n5rt24bs.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret: 6PnvyM2DObCTtL1CKvj_VTwq
spring.security.oauth2.client.registration.google.client-id: 654537341843-n12bopaohv8ua6nlm90thi4tem6jpasa.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret: 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
#spring.security.oauth2.client.registration.google.redirect-uri: https://{baseUrl}/{action}/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.google.redirect-uri: https://www.rollco7.com/{action}/oauth2/code/{registrationId}



logging:
    level:
        com.millky.blog: DEBUG

server:
    error:
        whitelabel:
            enabled: false